import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const RaptorMonoSemiBold = localFont({
  src: "../../public/fonts/RaptorMonoSemiBold.woff",
  variable: "--RaptorMonoSemiBold",
  display: "swap",
});

const RaptorTextSemiBold = localFont({
  src: "../../public/fonts/RaptorTextSemiBold.woff",
  variable: "--RaptorTextSemiBold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${RaptorMonoSemiBold.variable} ${RaptorTextSemiBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
